### ISSUE TITLE
Add Link to GitHub in the Header

### ISSUE THREAD

**Issue by TheConnMan** [TheConnMan/missd#1]

**Comment by Grumblesmith** [comment]
@TheConnMan is this still needed in the header? It looks like 9aecd82b58ec7a5d603be72444d06db623847414 added it to the menu.

**Comment by TheConnMan** [comment]
There's now a link to the version or latest commit which is on GitHub, but would it still be nice to have a GitHub icon link which takes you straight to the project or to the issues page?

**Comment by Grumblesmith** [comment]
The icon in the menu takes you right to the issues page. Do you want to have another icon in the header?

**Comment by TheConnMan** [comment]
That icon is probably enough.
